In [1]:
import numpy as np 

In [3]:
revenue = np.array ([[180,200,220],[24,36,40],[12,18,20]])
expenses = np.array([[80,90,100],[10,16,20],[8,10,10]])

In [4]:
profit = revenue - expenses

In [5]:
profit

array([[100, 110, 120],
       [ 14,  20,  20],
       [  4,   8,  10]])

In [6]:
price_per_unit = np.array([1000,400,1200])
unit = np.array([[30,40,50],[5,10,15],[2,5,7]])

In [7]:
price_per_unit*unit

array([[30000, 16000, 60000],
       [ 5000,  4000, 18000],
       [ 2000,  2000,  8400]])

In [9]:
np.dot(price_per_unit,unit)

array([34400, 50000, 64400])

In [10]:
revenues_usd = np.array([[200,220,250],[68,79,105],[110,140,180],[80,85,90]])

In [11]:
usd_to_inr_rate = 75

In [12]:
# Convert revenues to Indian Rupees
revenues_inr = revenues_usd * usd_to_inr_rate

In [14]:
print("Revenues in USD:", revenues_usd)
print("Revenues in INR:", revenues_inr)

Revenues in USD: [[200 220 250]
 [ 68  79 105]
 [110 140 180]
 [ 80  85  90]]
Revenues in INR: [[15000 16500 18750]
 [ 5100  5925  7875]
 [ 8250 10500 13500]
 [ 6000  6375  6750]]


In [16]:
flowers_sold = np.array([[50,60,25],[10,13,5],[40,70,52]])
prices_per_flower = np.array([20,30,15])

In [19]:
# Calculate total sales for each month
total_sales = np.dot(prices_per_flower,flowers_sold)

In [20]:
for i, month_sales in enumerate(total_sales):
    print(f"Total sales for Month {i + 1}: ${month_sales}")

Total sales for Month 1: $1900
Total sales for Month 2: $2640
Total sales for Month 3: $1430
