# Implementing Loss Function

### Mean Absolute Error (MAE)
### Mean Squared Error (MSE)
### Log loss or binary cross entropy

In [1]:
import numpy as np 

y_predicted = np.array ([1,1,0,0,1])
y_true = np.array ([0.30,0.7,1,0,0.5])

In [2]:
def mea(y_true,y_predicted):
    total_error = 0 
    for yt, yp in zip(y_true,y_predicted):
        print(yt, yp)

In [3]:
mea(y_true,y_predicted)

0.3 1
0.7 1
1.0 0
0.0 0
0.5 1


In [18]:
def mae(y_true,y_predicted):
    total_error = 0 
    for yt, yp in zip(y_true,y_predicted):
        total_error += abs(yt - yp)
    print ("Total error:",total_error)
    
    mae = total_error / len(y_true)
    print ("MAE:",mae)
    return mae

In [19]:
mae(y_true,y_predicted)

Total error: 2.5
MAE: 0.5


0.5

In [20]:
y_predicted - y_true

array([ 0.7,  0.3, -1. ,  0. ,  0.5])

In [21]:
np.abs(y_predicted - y_true)

array([0.7, 0.3, 1. , 0. , 0.5])

In [22]:
np.mean(np.abs(y_predicted - y_true))

0.5

In [23]:
np.sum(np.abs(y_predicted - y_true))

2.5

## Binary cross entropy

In [30]:
np.log([0.00000000001])

array([-25.32843602])

In [34]:
eplison = 1e-15

In [35]:
y_predicted

array([1, 1, 0, 0, 1])

In [36]:
y_predicted_new = [max(i,eplison) for i in y_predicted]
y_predicted_new

[1, 1, 1e-15, 1e-15, 1]

In [39]:
y_predicted_new = [min(i,1-eplison) for i in y_predicted_new]
y_predicted_new

[0.999999999999999, 0.999999999999999, 0, 0, 0.999999999999999]

In [42]:
y_predicted_new = np.array(y_predicted_new)
np.log(y_predicted_new)

/var/folders/t9/gf0xz31d2kg3q3dl2zfptkqc0000gn/T/ipykernel_44096/2029199556.py:2: RuntimeWarning: divide by zero encountered in log
  np.log(y_predicted_new)


array([-9.99200722e-16, -9.99200722e-16,            -inf,            -inf,
       -9.99200722e-16])

In [44]:
# expression with added safeguards
-np.mean(y_true * np.log(np.clip(y_predicted_new, 1e-15, 1)) + (1 - y_true) * np.log(np.clip(1 - y_predicted_new, 1e-15, 1)))

17.269388197455342

In [47]:
def log_loss (y_true, y_predicted):
    epsilon = 1e-15
    y_predicted_new = [max(i,epsilon) for i in y_predicted]
    y_predicted_new = [min(i,1-epsilon) for i in y_predicted_new]
    y_predicted_new = np.array(y_predicted_new)
    return -np.mean(y_true*np.log(y_predicted_new)+(1-y_true)*np.log(1-y_predicted_new))

In [48]:
log_loss(y_true, y_predicted)

17.2696280766844

## MSE

In [49]:
#Implementation of MSE without using numpy

def mse(y_true, y_predicted):
    total_error = 0 
    for yt, yp in zip(y_true, y_predicted):
        total_error += (yt - yp) ** 2

    mse_value = total_error / len(y_true)
    print("Total error:", total_error)
    print("MSE:", mse_value)
    return mse_value

In [51]:
mse (y_true,y_predicted)

Total error: 1.83
MSE: 0.366


0.366

In [53]:
#Implementation of MSE with the use of numpy
def mse(y_true, y_predicted):
    y_true_np = np.array(y_true)
    y_predicted_np = np.array(y_predicted)
    mse = np.mean((y_true_np - y_predicted_np) ** 2)
    return mse

In [56]:
print("Mean Squared Error (With NumPy):", mse(y_true, y_predicted))

Mean Squared Error (With NumPy): 0.366
